define([], function() {
  return {
    PropertyPaneDescription: "Below properties will help you manage your quiz questions and extra features that you can leverage.",
    BasicGroupName: "",
    ListCreationText: "Verifying the response list...",
    PlaceholderIconText: "Configure your Quick Quiz",
    PlaceholderDescription: "",
    PlaceholderButtonLabel: "Come on...",
    QuestionLoadingText: "Loading Poll data",
    SubmissionLoadingText: "Submission is inprogress",
    PlsWait: "Please wait...",
    PollDateLabel: "Display Quiz based on date",
    PollDateCalloutText: "Turning on will display the quiz based on the 'Start Date' & 'End Date'",
    PollQuestionsLabel: "Poll Questions:",
    PollQuestionsPanelHeader: "Poll Questions list",
    PollQuestionsManageButton: "Manage Questions Info",
    MsgAfterSubmissionLabel: "Success Message:",
    MsgAfterSubmissionDescription: "Message to display after successfull submission. Max of 150 characters are allowed.",
    MsgAfterSubmissionPlaceholder: "Message...",
    ResponseMsgToUserLabel: "Response Message:",
    ResponseMsgToUserDescription: "Message displayed once the user submitted the quiz. E.g., 'You voted for: <UserResponse>'",

    ResponseMsgToUserWrongLabel: "Response on Wrong Message:",
    ResponseMsgToUserWrongDescription: "Message displayed once the user submitted the quiz. E.g., 'Wrong Answer: <UserResponse>. Correct Answer: <CorrectAnswer>.'",

    ResponseMsgToUserPlaceholder: "Message...",
    DefaultResponseMsgToUser: "You answer to",
    SuccessfullVoteSubmission: "Thank you for your submission",
    FailedVoteSubmission: "Sorry, something wrong while submitting. Please try again after sometime.",
    BtnSumbitVote: "Submit",
    BtnSumbitVoteLabel: "Submit Button Text:",
    BtnSumbitVoteDescription: "Text to display on the submit button. Max of 50 characters are allowed",
    BtnSumbitVotePlaceholder: "Submit button text...",
    SubmitValidationMessage: "Please select any option!",
    ChartFieldLabel: "Preferred Chart Type",
    ChartFieldCalloutText: "Select preferrable chart type",
    NoPollMsgLabel: "No Quiz Message:",
    NoPollMsgDescription: "Message to be displayed when there is no Quiz.",
    NoPollMsgPlaceholder: "Message...",
    NoPollMsgDefault: "Sorry, no quiz to display!",

    Q_Title_Title: "Question Title",
    Q_Title_Placeholder: "Question Title...",
    Q_Options_Title: "Choices",
    Q_Options_Placeholder: "Choices separated by comma",
    MultiChoice_Title: "Multi Selection",
    Q_StartDate_Title: "Start Date",
    Q_EndDate_Title: "End Date"
  }
});