trigger:
  branches:
    include:
    - main
  paths:
    include:
      - 'SPFx/WebPart/MillimanRPSANomination/*'
      - 'SPFx/Libraries/Milliman.PDNomination.Library/*'
    exclude:
      - SPFx/Libraries/Milliman.PDNomination.Library/README.md

pr : none      

resources:
  repositories:
  - repository: azure-pipelines-templates
    type: git
    name: azure-pipelines-templates

variables:
  - group: MillimanDevOpsSecrets
  - group: MillimanDevOpsAzureFunctionSecrets
  - name: node_version
    value: '10.x'
  - name: package_manager
    value: 'npm'
  - name: dev_site_url
    value: 'https://millimandev.sharepoint.com/sites/AppCatalog'
  - name: uat_site_url
    value: 'https://millimantest.sharepoint.com/sites/AppCatalog'
  - name: prod_site_url
    value: 'https://milliman.sharepoint.com/sites/appcatalog'
  - name: stage_completion_ack_recipients
    value: 'varun.jindal@milliman.com;c-sindhuja.togaru@milliman.com;xavier.vanwindekens@milliman.com'
  - name: gulpfile_parent_folder
    value: 'SPFx/Libraries/Milliman.PDNomination.Library'

stages:
- stage: Build
  dependsOn: []
  jobs:
    - template: SharePoint/build.yml@azure-pipelines-templates
      parameters:
        working_directory: ${{ variables.gulpfile_parent_folder }}
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}
        gulp_tasks: []
        gulp_build_extra_args: ''
        gulp_bundle_extra_args: '--warnoff'
        gulp_package_extra_args: ''
- stage: Test
  dependsOn: []
  jobs:
    - template: SharePoint/test.yml@azure-pipelines-templates
      parameters:
        working_directory: ${{ variables.gulpfile_parent_folder }}
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}

- stage: Deploy_Dev
  dependsOn:
    - Build
    - Test
  jobs:
    - template: SharePoint/deploy.yml@azure-pipelines-templates
      parameters:
        display_name: Deploy to development
        target_environment: Dev
        node_version: ${{ variables.node_version }}
        app_Id: $(DevAppId)
        tenant_Id: $(DevTenantId)
        m365_app_catalog_site_url: ${{ variables.dev_site_url }}
        m365cli_app_catalog_scope: tenant
        m365cli_deploy_extra_arguments: ''
        stage_outcome_recipients: ${{ variables.stage_completion_ack_recipients }}
- stage: Deploy_UAT
  dependsOn:
    - Build
    - Test
    - Deploy_Dev
  jobs:
    - template: SharePoint/deploy.yml@azure-pipelines-templates
      parameters:
        display_name: Deploy to staging
        target_environment: UAT
        node_version: ${{ variables.node_version }}
        app_Id: $(UATAppId)
        tenant_Id: $(UATTenantId)
        m365_app_catalog_site_url: ${{ variables.uat_site_url }}
        m365cli_app_catalog_scope: tenant
        m365cli_deploy_extra_arguments: ''
        stage_outcome_recipients: ${{ variables.stage_completion_ack_recipients }}
- stage: Deploy_Prod
  dependsOn:
    - Build
    - Test
    - Deploy_UAT
  jobs:
    - template: SharePoint/deploy.yml@azure-pipelines-templates
      parameters:
        display_name: Deploy to production
        target_environment: Production
        node_version: ${{ variables.node_version }}
        app_Id: $(ProdAppId)
        tenant_Id: $(ProdTenantId)
        m365_app_catalog_site_url: ${{ variables.prod_site_url }}
        m365cli_app_catalog_scope: tenant
        m365cli_deploy_extra_arguments: '--skipFeatureDeployment'
        stage_outcome_recipients: ${{ variables.stage_completion_ack_recipients }}
